### ISSUE TITLE
Convert hash to screen name?

### ISSUE THREAD

**Issue by dnpthree** [Shiqan/fortnite-replay-reader#14]
Hi, not sure where else to post this, but is anyone aware of a way to convert a hash to a screen name? I'd like to convert the following to a screen name and in previous replay versions a screen name was present but as of lately its a hash

![image](https://user-images.githubusercontent.com/51075188/62936257-5547f000-bd97-11e9-8d4e-f7cb23b80cc1.png)

**Comment by Kuinox** [comment]
You have to use the fortnite API.
These "hash" are Epic ID.

**Comment by dnpthree** [comment]
awesome... thanks man. Do you happen to have any docs that could help get me started on how to query against Epic's API?

**Comment by Kuinox** [comment]
The epic API is closed source and there is no official docs to how querry it.   
But a lot of peoples reversed engineered it and made some unofficial docs.
