### ISSUE TITLE
Missing weapon types

### ISSUE THREAD

**Issue by dtaivpp** [Shiqan/fortnite-replay-reader#17]
Hey Shiqan, just running this and noticed there are missing weapon types. Where does one typically find these at? If there's a good source I can update and submit pr. 

ERROR:ray.logging:Missing weapon   type 48
ERROR:ray.logging:Missing   weapon type 17
ERROR:ray.logging:Missing weapon   type 16
ERROR:ray.logging:Missing   weapon type 30
ERROR:ray.logging:Missing weapon   type 13

**Comment by Kuinox** [comment]
Weapons types are not reliable, we seen the number changing between versions when Epic added/removed weapons, i suspected that someday a collision would occur (it should have happened now, but i didn't checked).  
If you want reliable weapon number, you need to get the weapons ID for every weapons, every update, or more simply, when we will read network packets correctly. There is probably the correct weapons name inside the packets.
