### ISSUE TITLE
Integration

### ISSUE THREAD

**Issue by alathrop99** [Shiqan/fortnite-replay-reader#18]
I apologize for the unprofessional manner in which I'm contacting you, but I wasn't sure how else to reach out; as such I've created this request. I've been interested in your work here for some time now and have used it previously to obtain data. I was hoping to speak with you further about the parser. If you have some time to speak you can contact me via email at a.lathrop@prodigyanalytics.com. Thank you and, again, I apologize for the manner in which I'm trying to reach you.

**Comment by Kuinox** [comment]
We got a Discord server to discuss about the Fortnite parsers: 
https://discordapp.com/invite/p5CMqJC
See you soon.
