### ISSUE TITLE
Player type field no longer being used

### ISSUE THREAD

**Issue by stevegee58** [Shiqan/fortnite-replay-reader#24]
Looks like all that work to decode the player type field was for nothing.  All players including bots are 0x11.  Also bots have hashes instead of names just like regular players.
Is the C# decompressor able to distinguish bot versus human players?  I'm particularly interested in this because I'm doing stats on bot percentage versus player level.  e.g. beginner players have 80% bot lobbies.

**Comment by Shiqan** [comment]
Completely missed this one.
Anyway, had a look at one of my latest replays (4 days ago) and I still get 0x03 for player type fields.
Regarding the C# versions, yes, we are able to distinguish bots vs human players. In fact, we dont even need the player elimination events because we get the same information (and much more) in the network packets.

**Comment by stevegee58** [comment]
Did you run your latest replays through this Python script or the C# version?
I just tried a game from today and the Python script still says every player is type 0x11

**Comment by Shiqan** [comment]
I did not, but did it just now and I do get 0x03 and 0x11 (no 0x10 though). If you're on Discord yo can send me your replay(s) and I can run them through the C# version to see what's up. Right now, I'm not sure if there is an issue at least :)

**Comment by stevegee58** [comment]
I've attached my zipped replay file:
[UnsavedReplay-2019.12.27-11.00.55.replay.zip](https://github.com/Shiqan/fortnite-replay-reader/files/4005899/UnsavedReplay-2019.12.27-11.00.55.replay.zip)

Maybe I'm not playing with bots any more but I find that hard to believe since I'm a horrible player :D

**Comment by Shiqan** [comment]
Even running it through the python version results in 0x03?
```python

f = r'./UnsavedReplay-2019.12.27-11.00.55.replay'
with Reader(f) as replay:
    print('breakpoint here')
```

results in 3 bots being eliminated:
```python


> len([i for i in replay.eliminations if i.eliminator.is_player])
94
> len([i for i in replay.eliminations if not i.eliminator.is_player])
3
> len([i for i in replay.eliminations if not i.eliminated.is_player])
0
> len(replay.eliminations)
97
```

I'm on the develop branch, no local changes. Am I missing something? 😕

**Comment by stevegee58** [comment]
Thanks for your help.  I found a bug in the way I was counting bots and humans so now my program agrees with your results.

It seems odd that the number of eliminator bots is 3 but the eliminated bots is 0.  I know for sure that I killed at least 1 bot just based on how bad they sucked.
