### ISSUE TITLE
Is there a way to get when a player is rebooted or revived?

### ISSUE THREAD

**Issue by Keineru** [Shiqan/fortnite-replay-reader#25]
I'm developing an web app for custom competitions in order to get a fast calculation of points and positions in a match, but it only works for solo matches. For duo and squad matches is necessary to know when a player is rebooted or revived.

So, is this information available in the replay file?

**Comment by Shiqan** [comment]
Yes, this is possible but not in (yet) in the Python variant.
Please have a look at the [C# version](https://github.com/Shiqan/FortniteReplayDecompressor). Especially the forked version from @SL-x-TnT.

**Comment by SL-x-TnT** [comment]
My version doesn't have revives/reboots parsed out yet, but it does have placements.
