### ISSUE TITLE
support for season 12

### ISSUE THREAD

**Issue by gelzis** [Shiqan/fortnite-replay-reader#28]
Hi. Is support for season 12 replays coming? seems that it has issues atm, at least with the `knocked` attribute on eliminations and maybe something else is affected.

**Comment by Shiqan** [comment]
Hi, Epic has added the option to encrypt replay chunks which is not yet added to the Python version.
You can see the decryption process in this commit by [SL-x-TnT](https://github.com/SL-x-TnT/FortniteReplayDecompressor/commit/b0b5501167a5e693c78f7118aabcdb6df11fa60a)
This is for our C# parser though, needs to be ported to Python. I don't think I'll make time for this in the foreseeable future.

**Comment by gelzis** [comment]
thanks for the info, will try to get the C# version working then.
