### ISSUE TITLE
Interested in your work

### ISSUE THREAD

**Issue by kinch2002** [Shiqan/fortnite-replay-reader#31]
Sorry, this is totally the wrong place for this, but I don't know how else to contact you.
I'm a Fortnite analyst and I'm interested in your work on Replay files.
Please contact me on twitter @kinchanalytics or email kinchanalytics@gmail.com

**Comment by Shiqan** [comment]
Documentation is available at [readthedocs.org](https://fortnitereplaydecompressor.readthedocs.io/en/latest/?badge=latest). For any other question you can join our [Discord server](https://discord.gg/p5CMqJC)!
