### ISSUE TITLE
Improve idea

### ISSUE THREAD

**Issue by leomelki** [Shiqan/fortnite-replay-reader#4]
Hello, is it possible to get the differents players that are in a same duo/squad and the bus driver thanks message ?
Thank you very much and have a good day !

**Comment by Shiqan** [comment]
Hi @leomelki 
Unfortunately, that data is not so easy accessible. I'm working on it though! Once I have successfully parsed the entire replay, I'll probably open source that part as well. But dont expect it anytime soon :)

**Comment by leomelki** [comment]
Oh, thank you for responding ! Good luck, you're doing an amazing job !
