### ISSUE TITLE
NPM?

### ISSUE THREAD

**Issue by markito12** [Shiqan/fortnite-replay-reader#5]
Wondering if u had made a npm version, i use to work mostly with nodejs

**Comment by markito12** [comment]
and i was wondering if replays had more content

**Comment by Shiqan** [comment]
No plans for a npm package for now. You can use [tpatel's version](https://github.com/tpatel/fortnite-replay-reader). And yes, replays contain a lot of information, but we cant read it just yet.
Trying to read it in this c# repo: [FortniteReplayDecompressor](https://github.com/Shiqan/FortniteReplayDecompressor)

**Comment by markito12** [comment]
ok! last thing, to get the owner of the replay?
